### ISSUE TITLE
Critical exception handling a packet on channel steamcraft causes fatal error

### ISSUE THREAD

**Issue by cocopuffs99** [Esteemed-Innovation/Flaxbeards-Steam-Power#268]
Found a possible fatal server shutdown bug with packet handling? Not sure.  BCAdditions found and fixed similar bug a few days ago; may be helpful:  https://github.com/BCA-Team/Buildcraft-Additions/issues/384#issuecomment-94167284

[18/4/2015 23:10:07 PM] java.lang.NullPointerException
[18/4/2015 23:10:07 PM]         at flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler.handleCamoPacket(SteamcraftServerPacketHandler.java:165) ~[SteamcraftServerPacketHandler.class:?]
[18/4/2015 23:10:07 PM]         at flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler.onServerPacket(SteamcraftServerPacketHandler.java:329) ~[SteamcraftServerPacketHandler.class:?]
[18/4/2015 23:10:07 PM]         at cpw.mods.fml.common.eventhandler.ASMEventHandler_1049_SteamcraftServerPacketHandler_onServerPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
[18/4/2015 23:10:07 PM]         at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[18/4/2015 23:10:07 PM]         at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
[18/4/2015 23:10:07 PM]         at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:?]
[18/4/2015 23:10:07 PM]         at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:?]
[18/4/2015 23:10:07 PM]         at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:?]
[18/4/2015 23:10:07 PM]         at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
[18/4/2015 23:10:07 PM]         at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
[18/4/2015 23:10:07 PM]         at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
[18/4/2015 23:10:07 PM]         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]

Full log: http://pastebin.com/Es6YpnRp

**Comment by elifoster** [comment]
Are you running a version earlier than 0.28.6?

**Comment by cocopuffs99** [comment]
I'm using 0.28.7

**Comment by elifoster** [comment]
Huh. I guess we'll need to find where else we are catching Exception rather than specific exceptions. Yo @Strikingwolf do you wanna do this again? :P
