### ISSUE TITLE
Crash with Exosuit and Botania.

### ISSUE THREAD

**Issue by PaperTriangle** [Esteemed-Innovation/Flaxbeards-Steam-Power#297]
Wearing an Exosuit Headpiece without the Chestpiece while Botania is installed causes a crash.

```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 8/10/15 8:45 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at flaxbeard.steamcraft.handler.SteamcraftEventHandler.onDrawScreen(SteamcraftEventHandler.java:390)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_77_SteamcraftEventHandler_onDrawScreen_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at flaxbeard.steamcraft.handler.SteamcraftEventHandler.onDrawScreen(SteamcraftEventHandler.java:390)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_77_SteamcraftEventHandler_onDrawScreen_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['PaperTriangle'/12, l='MpServer', x=334.50, y=65.62, z=-469.50]]
	Chunk stats: MultiplayerChunkCache: 565, 565
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (332,64,-464), Chunk: (at 12,4,0 in 20,-29; contains blocks 320,0,-464 to 335,255,-449), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 268 game time, 268 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 111 total; [EntityClientPlayerMP['PaperTriangle'/12, l='MpServer', x=334.50, y=65.62, z=-469.50], EntitySquid['Squid'/34, l='MpServer', x=341.56, y=57.31, z=-403.81], EntitySquid['Squid'/35, l='MpServer', x=333.22, y=55.16, z=-409.13], EntitySquid['Squid'/33, l='MpServer', x=334.34, y=57.34, z=-407.75], EntitySquid['Squid'/36, l='MpServer', x=333.94, y=57.34, z=-410.88], EntitySquid['Squid'/137, l='MpServer', x=293.94, y=58.09, z=-466.34], EntitySquid['Squid'/136, l='MpServer', x=291.84, y=58.34, z=-463.03], EntitySquid['Squid'/139, l='MpServer', x=296.25, y=58.31, z=-465.44], EntitySquid['Squid'/138, l='MpServer', x=300.38, y=58.03, z=-456.50], EntitySquid['Squid'/141, l='MpServer', x=293.94, y=56.25, z=-458.50], EntitySquid['Squid'/140, l='MpServer', x=293.59, y=57.34, z=-463.66], EntitySquid['Squid'/133, l='MpServer', x=302.38, y=56.66, z=-464.22], EntitySquid['Squid'/135, l='MpServer', x=290.09, y=58.34, z=-461.78], EntitySquid['Squid'/134, l='MpServer', x=297.81, y=57.66, z=-464.09], EntitySquid['Squid'/171, l='MpServer', x=276.19, y=49.34, z=-433.50], EntitySquid['Squid'/170, l='MpServer', x=277.38, y=49.34, z=-433.50], EntitySquid['Squid'/169, l='MpServer', x=280.72, y=49.34, z=-432.47], EntitySquid['Squid'/168, l='MpServer', x=283.25, y=48.38, z=-428.44], EntitySquid['Squid'/175, l='MpServer', x=287.50, y=49.31, z=-428.13], EntitySquid['Squid'/173, l='MpServer', x=276.88, y=45.09, z=-424.16], EntitySquid['Squid'/172, l='MpServer', x=276.34, y=48.31, z=-429.53], EntitySquid['Squid'/167, l='MpServer', x=283.75, y=48.38, z=-426.25], EntitySquid['Squid'/166, l='MpServer', x=283.47, y=48.22, z=-429.56], EntitySquid['Squid'/219, l='MpServer', x=273.16, y=54.31, z=-410.38], EntitySquid['Squid'/224, l='MpServer', x=277.69, y=51.00, z=-414.31], EntitySquid['Squid'/373, l='MpServer', x=303.50, y=59.78, z=-419.66], EntitySquid['Squid'/372, l='MpServer', x=302.97, y=59.34, z=-423.28], EntitySquid['Squid'/375, l='MpServer', x=310.78, y=61.38, z=-421.44], EntitySquid['Squid'/374, l='MpServer', x=302.31, y=61.19, z=-424.19], EntitySquid['Squid'/381, l='MpServer', x=305.53, y=61.34, z=-426.03], EntitySquid['Squid'/380, l='MpServer', x=293.50, y=61.34, z=-417.03], EntitySquid['Squid'/383, l='MpServer', x=301.13, y=61.28, z=-423.63], EntitySquid['Squid'/382, l='MpServer', x=304.63, y=60.34, z=-423.22], EntitySquid['Squid'/377, l='MpServer', x=308.41, y=61.34, z=-415.88], EntitySquid['Squid'/376, l='MpServer', x=299.59, y=59.91, z=-417.09], EntitySquid['Squid'/379, l='MpServer', x=300.56, y=58.75, z=-412.78], EntitySquid['Squid'/378, l='MpServer', x=305.66, y=61.38, z=-418.66], EntityBat['Bat'/472, l='MpServer', x=343.72, y=28.20, z=-495.66], EntitySpider['Spider'/494, l='MpServer', x=410.84, y=39.00, z=-533.50], EntityCreeper['Creeper'/574, l='MpServer', x=328.50, y=38.00, z=-538.50], EntityZombie['Zombie'/522, l='MpServer', x=308.50, y=51.00, z=-532.50], EntityCreeper['Creeper'/532, l='MpServer', x=360.00, y=52.00, z=-531.53], EntityZombie['Zombie'/534, l='MpServer', x=357.44, y=50.00, z=-531.47], EntitySkeleton['Skeleton'/528, l='MpServer', x=315.50, y=12.00, z=-545.34], EntityCreeper['Creeper'/531, l='MpServer', x=356.38, y=50.00, z=-532.34], EntityBat['Bat'/578, l='MpServer', x=315.50, y=16.10, z=-525.75], EntityBat['Bat'/591, l='MpServer', x=374.73, y=37.51, z=-505.89], EntityBat['Bat'/595, l='MpServer', x=354.83, y=50.48, z=-532.40], EntityBat['Bat'/687, l='MpServer', x=386.24, y=24.08, z=-546.33], EntityBat['Bat'/685, l='MpServer', x=312.85, y=16.42, z=-500.70], EntityBat['Bat'/684, l='MpServer', x=303.48, y=20.04, z=-508.93], EntityEnderman['Enderman'/680, l='MpServer', x=333.00, y=21.00, z=-523.41], EntityZombie['Zombie'/677, l='MpServer', x=311.38, y=18.00, z=-486.97], EntityBat['Bat'/692, l='MpServer', x=312.92, y=46.19, z=-490.98], EntityBat['Bat'/688, l='MpServer', x=386.27, y=25.05, z=-543.26], EntityZombie['Zombie'/746, l='MpServer', x=304.50, y=47.00, z=-522.50], EntityBat['Bat'/751, l='MpServer', x=293.03, y=22.84, z=-460.29], EntityCreeper['Creeper'/749, l='MpServer', x=296.50, y=22.00, z=-512.50], EntitySkeleton['Skeleton'/743, l='MpServer', x=367.50, y=47.00, z=-464.50], EntityBat['Bat'/753, l='MpServer', x=292.54, y=21.45, z=-513.51], EntityWitch['Witch'/759, l='MpServer', x=307.94, y=16.00, z=-544.50], EntityBat['Bat'/705, l='MpServer', x=332.19, y=55.05, z=-527.51], EntityBat['Bat'/706, l='MpServer', x=294.64, y=45.01, z=-453.53], EntityBat['Bat'/812, l='MpServer', x=315.75, y=21.03, z=-428.13], EntityBat['Bat'/813, l='MpServer', x=293.44, y=28.42, z=-458.53], EntityBat['Bat'/774, l='MpServer', x=359.65, y=53.62, z=-524.50], EntityZombie['Zombie'/855, l='MpServer', x=301.50, y=19.00, z=-511.50], EntitySkeleton['Skeleton'/853, l='MpServer', x=312.50, y=17.00, z=-528.50], EntityCreeper['Creeper'/862, l='MpServer', x=367.94, y=19.00, z=-434.28], EntityCreeper['Creeper'/861, l='MpServer', x=375.50, y=23.00, z=-447.50], EntityEnderman['Enderman'/952, l='MpServer', x=319.06, y=30.00, z=-532.69], EntityEnderman['Enderman'/953, l='MpServer', x=318.25, y=30.00, z=-533.56], EntityZombie['Zombie'/950, l='MpServer', x=316.50, y=30.00, z=-527.50], EntityZombie['Zombie'/951, l='MpServer', x=318.13, y=30.00, z=-532.13], EntitySkeleton['Skeleton'/929, l='MpServer', x=306.50, y=14.00, z=-512.50], EntityZombie['Zombie'/1008, l='MpServer', x=304.50, y=18.00, z=-515.50], EntitySkeleton['Skeleton'/1009, l='MpServer', x=310.50, y=18.00, z=-512.50], EntityZombie['Zombie'/978, l='MpServer', x=318.56, y=37.00, z=-534.70], EntityItem['item.tile.mushroom13'/4832, l='MpServer', x=385.88, y=28.13, z=-413.47], EntityZombie['Zombie'/976, l='MpServer', x=314.63, y=40.00, z=-535.72], EntityZombie['Zombie'/977, l='MpServer', x=314.50, y=40.00, z=-536.78], EntitySpider['Spider'/982, l='MpServer', x=310.75, y=40.00, z=-540.19], EntitySpider['Spider'/980, l='MpServer', x=312.34, y=40.00, z=-542.50], EntitySpider['Spider'/981, l='MpServer', x=316.22, y=41.00, z=-533.19], EntityZombie['Zombie'/975, l='MpServer', x=310.50, y=40.00, z=-541.50], EntityItem['item.tile.mushroom'/4862, l='MpServer', x=389.88, y=27.13, z=-414.13], EntitySpider['Spider'/1113, l='MpServer', x=317.97, y=16.00, z=-541.94], EntitySpider['Spider'/1112, l='MpServer', x=314.09, y=15.00, z=-539.94], EntityZombie['Zombie'/1114, l='MpServer', x=314.69, y=12.00, z=-529.88], EntityZombie['Zombie'/1036, l='MpServer', x=269.63, y=15.00, z=-546.94], EntitySkeleton['Skeleton'/1037, l='MpServer', x=298.13, y=20.00, z=-486.50], EntitySkeleton['Skeleton'/1038, l='MpServer', x=295.50, y=24.00, z=-476.50], EntityZombie['Zombie'/1039, l='MpServer', x=387.50, y=25.00, z=-544.50], EntitySkeleton['Skeleton'/1052, l='MpServer', x=296.50, y=31.00, z=-482.50], EntityCreeper['Creeper'/1041, l='MpServer', x=318.50, y=42.00, z=-525.50], EntityZombie['Zombie'/1057, l='MpServer', x=310.50, y=15.00, z=-502.50], EntityZombie['Zombie'/1087, l='MpServer', x=292.50, y=40.00, z=-490.50], EntityZombie['Zombie'/1169, l='MpServer', x=355.50, y=15.00, z=-414.50], EntitySkeleton['Skeleton'/1180, l='MpServer', x=387.50, y=27.00, z=-398.50], EntityEnderman['Enderman'/1212, l='MpServer', x=320.50, y=17.00, z=-523.50], EntityZombie['Zombie'/1313, l='MpServer', x=291.09, y=20.00, z=-489.69], EntitySpider['Spider'/1314, l='MpServer', x=292.84, y=20.00, z=-488.13], EntitySpider['Spider'/1316, l='MpServer', x=294.22, y=20.00, z=-485.19], EntityCreeper['Creeper'/1318, l='MpServer', x=291.50, y=20.00, z=-486.25], EntityCreeper['Creeper'/1319, l='MpServer', x=290.50, y=20.00, z=-487.50], EntityWitch['Witch'/1625, l='MpServer', x=292.50, y=31.00, z=-449.50], EntityCreeper['Creeper'/1624, l='MpServer', x=298.50, y=31.00, z=-452.50], EntityCreeper['Creeper'/1619, l='MpServer', x=288.50, y=24.00, z=-471.50], EntityCreeper['Creeper'/1618, l='MpServer', x=288.47, y=24.00, z=-469.00], EntityCreeper['Creeper'/1623, l='MpServer', x=323.50, y=21.00, z=-529.50], EntityCreeper['Creeper'/1622, l='MpServer', x=316.88, y=23.00, z=-532.22]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8 (amd64) version 6.2
	Java Version: 1.7.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 252650416 bytes (240 MB) / 571998208 bytes (545 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m -XX:PermSize=128m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Botania{r1.7-208} [Botania] (Botania r1.7-208.jar) 
	UCHIJAAAA	Steamcraft{0.28.9} [Flaxbeard's Steam Power] (Flaxbeard'sSteamPower-1.7.10-0.28.9.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.06' Renderer: 'GeForce GTX 660/PCIe/SSE2'
	Launched Version: MultiMC5
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 660/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.06, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```

**Comment by elifoster** [comment]
I don't think this bug actually has anything to do with Botania.

**Comment by PaperTriangle** [comment]
It only occurs while Botania is installed, and the line number is for code within "if (CrossMod.BOTANIA)". It just looks like there's a check for equipment slot 4 being null, but then it actually uses equipment slot 3…

**Comment by elifoster** [comment]
Ah. I just assumed it was a non-Botania issue due to the stacktrace.

**Comment by elifoster** [comment]
Oh yeah this bug should be an easy fix.

**Comment by PaperTriangle** [comment]
Glad to hear, was a super accidental find! Hopefully my Internet won't keep cutting out during my forge setup and I can submit a pull request next time.
