### ISSUE TITLE
Network bandwidth overload

### ISSUE THREAD

**Issue by LemADEC** [Esteemed-Innovation/Flaxbeards-Steam-Power#344]
When having just Flaxbeard'sSteamPower-1.7.10-0.28.12 and Forge, just connecting to a Vanilla server, my client upload bandwidth raise to 10 kB/s.
When I do the same without the mod, I'm seating around 1 kB/s.
Connecting to an server with the mod doesn't change the result.

According to Opis, the related packet is:
C17PacketCustomPayload 0 41,00 packet/s 10,573 KiB/s 936,769 KiB

I've seen a lot of changes in the code since Nov 7th version. Could we get a more recent binary?

**Comment by elifoster** [comment]
Keep your eye on the 0.29.0 milestone for the next release. The bandwidth issue has been reported before, so I'll take a look when I get a chance.

**Comment by elifoster** [comment]
Hm, weird. "C17PacketCustomPayload" is only referenced once in the code, and only in a comment. I guess I'll use this issue as a reason to learn more about Forge/MC networking/packets.

**Comment by LemADEC** [comment]
From our last 6 months playing with the mod on our public modpack, we had a few weird server crashes related to ItemSteamcraftBook, about once a month.
From a quick check in vanilla, C17PacketCustomPayload is used when player joins the world, edits or signs a book, select trade, sets command blocks commands, changes beacon effect, changes item name.

**Comment by elifoster** [comment]
I'd appreciate that other server crash bug being reported with the crash log, because that sounds pretty serious.

And we don't handle any of those things, except maybe when a player joins the world or changes an item name (Steam Hammer thing). So it's really weird that that is the problematic packet... Are you sure there are no other packets listed by OPIS that are causing bandwidth issues?

**Comment by LemADEC** [comment]
Opis is pretty explicit on which packet is causing the issue:
Inbound:
C17PacketCustomPayload	0	41,00 packet/s	10,573 KiB/s	4,376 MiB

I'll check up those other crashes. I think there was at least 2 different patterns but it was always about the book. We weren't able to reproduce it, so it's on hold.
Pattern 1
```
java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149694_d(Lnet/minecraft/world/World;III)Lnet/minecraft/item/Item;
        at net.minecraft.block.Block.getPickBlock(Block.java:1819)
        at net.minecraft.block.Block.getPickBlock(Block.java:1814)
        at flaxbeard.steamcraft.item.ItemSteamcraftBook.func_77648_a(ItemSteamcraftBook.java:32)
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:530)
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:152)
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:495)
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)
```

Pattern 2
```
java.lang.NoClassDefFoundError: flaxbeard/steamcraft/gui/GuiSteamcraftBook
        at flaxbeard.steamcraft.item.ItemSteamcraftBook.func_77648_a(ItemSteamcraftBook.java:38)
        at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:530)
        at net.minecraft.item.ItemStack.func_77943_a(ItemStack.java:152)
        at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:495)
        at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:853)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
        at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: flaxbeard.steamcraft.gui.GuiSteamcraftBook
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
        ... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 20 more
```

Observed with Flaxbeard'sSteamPower-1.7.10-0.28.7 and Flaxbeard'sSteamPower-1.7.10-0.28.10 .
I'll upload full logs in separate cases later on

**Comment by LemADEC** [comment]
Here's the 3rd pattern that happens when connecting to the server. Unlike the first 2 patterns, it's just kicking the player instead of crashing the server:
```
[15:30:03 INFO]: Joined EntityPlayer of name: LemADEC
[15:30:03 INFO]: Sending mutations to player: LemADEC
[15:30:03 INFO]: Player EntityPlayerMP['LemADEC'/589681, l='Merlin', x=614.93, y=61.50, z=-243.25](LemADEC at 614.9263499262527,61.5,-243.25) connected. Sending ping
[15:30:03 INFO]: npe choco
[15:30:03 ERROR]: Exception caught during firing event cpw.mods.fml.common.network.FMLNetworkEvent$ServerCustomPacketEvent@598a8db5:
java.lang.ClassCastException: net.minecraft.entity.item.EntityItemFrame cannot be cast to net.minecraft.entity.player.EntityPlayer
>       at flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler.handleNoSpacePacket(SteamcraftServerPacketHandler.java:239) ~[SteamcraftServerPacketHandler.class:?]
>       at flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler.onServerPacket(SteamcraftServerPacketHandler.java:324) ~[SteamcraftServerPacketHandler.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_529_SteamcraftServerPacketHandler_onServerPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) [FMLEventChannel.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) [NetworkEventFiringHandler.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) [NetworkEventFiringHandler.class:1.7.10-1614.UNOFFICIAL]
>       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
>       at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
>       at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
>       at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.UNOFFICIAL]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
[15:30:03 ERROR]: Index: 1 Listeners:
[15:30:03 ERROR]: 0: NORMAL
[15:30:03 ERROR]: 1: ASM: flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler@5f93e4f4 onServerPacket(Lcpw/mods/fml/common/network/FMLNetworkEvent$ServerCustomPacketEvent;)V
[15:30:03 ERROR]: NetworkEventFiringHandler exception
java.lang.ClassCastException: net.minecraft.entity.item.EntityItemFrame cannot be cast to net.minecraft.entity.player.EntityPlayer
>       at flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler.handleNoSpacePacket(SteamcraftServerPacketHandler.java:239) ~[SteamcraftServerPacketHandler.class:?]
>       at flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler.onServerPacket(SteamcraftServerPacketHandler.java:324) ~[SteamcraftServerPacketHandler.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_529_SteamcraftServerPacketHandler_onServerPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:1.7.10-1614.UNOFFICIAL]
>       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
>       at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
>       at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
>       at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.UNOFFICIAL]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
[15:30:03 ERROR]: There was a critical exception handling a packet on channel steamcraft
java.lang.ClassCastException: net.minecraft.entity.item.EntityItemFrame cannot be cast to net.minecraft.entity.player.EntityPlayer
>       at flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler.handleNoSpacePacket(SteamcraftServerPacketHandler.java:239) ~[SteamcraftServerPacketHandler.class:?]
>       at flaxbeard.steamcraft.packet.SteamcraftServerPacketHandler.onServerPacket(SteamcraftServerPacketHandler.java:324) ~[SteamcraftServerPacketHandler.class:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler_529_SteamcraftServerPacketHandler_onServerPacket_ServerCustomPacketEvent.invoke(.dynamic) ~[?:?]
>       at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.FMLEventChannel.fireRead(FMLEventChannel.java:103) ~[FMLEventChannel.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:30) ~[NetworkEventFiringHandler.class:1.7.10-1614.UNOFFICIAL]
>       at cpw.mods.fml.common.network.NetworkEventFiringHandler.channelRead0(NetworkEventFiringHandler.java:18) ~[NetworkEventFiringHandler.class:1.7.10-1614.UNOFFICIAL]
>       at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
>       at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
>       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
>       at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
>       at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1614.UNOFFICIAL]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
[15:30:03 INFO]: LemADEC lost connection: A fatal error has occured, this connection is terminated
```

**Comment by elifoster** [comment]
That third crash has been fixed in 0.29.0.

**Comment by LemADEC** [comment]
good to know

How many tickets do you want for the first 2 patterns?

**Comment by elifoster** [comment]
Let's start with 2, but I'll close one if we find out that they are the same problem.

**Comment by LemADEC** [comment]
#345 and #346 have been created for patterns 1 and 2
