### ISSUE TITLE
Book-Hammer crash

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#347]
Testing some new networking things, I had this crash when I used the book on the hammer:
```
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
	at flaxbeard.steamcraft.item.ItemSteamcraftBook.onItemUse(ItemSteamcraftBook.java:42)
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:507)
	at net.minecraft.item.ItemStack.tryPlaceItemIntoWorld(ItemStack.java:142)
	at net.minecraft.server.management.ItemInWorldManager.activateBlockOrUseItem(ItemInWorldManager.java:422)
	at net.minecraft.network.NetHandlerPlayServer.processPlayerBlockPlacement(NetHandlerPlayServer.java:593)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:74)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.processPacket(C08PacketPlayerBlockPlacement.java:122)
	at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:241)
	at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:182)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:726)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)
```

Note that it occurred AFTER the page had loaded.

**Comment by elifoster** [comment]
Unconfirmed because it has not been confirmed on the master branch.

**Comment by elifoster** [comment]
Might be related to #362 as it mentions the server in the crash report, as well as a line that references `Minecraft`, a client-side only class.
