### ISSUE TITLE
Internal Server Error when using the Pyrophobic Coatings in the Exosuit Boots to float on Lava while playing on a Server

### ISSUE THREAD

**Issue by kindlich** [Esteemed-Innovation/Flaxbeards-Steam-Power#455]
## Description

Well, the title sais it all xD
When having the Pyrophobic Coatings upgrade (the one allowing you to walk on lava) in your ExoSuit, you get an internal Server Error when touching lava.
It only happens on a server though...
Tested with only FSP and it still happens!
## Base information
- Minecraft version: 1.7.10
- Minecraft Forge version: 1614
- Flaxbeard's Steam Power version: 0.29.3
## Crash report

Doesn't tell much but this is the fml-client-latest.log from when I try to join the server where that happened...

```
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Server FML protocol version 2, 4 byte dimension received 0
[20:09:49] [Netty Client IO #9/TRACE] [FML/]: $ServerHello->FMLHandshakeClientState$2:HELLO
[20:09:49] [Netty Client IO #9/INFO] [FML/]: Server protocol version 2
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Received override dimension 0
[20:09:49] [Netty Client IO #9/TRACE] [FML/]: $ModList:5 mods->FMLHandshakeClientState$3:WAITINGSERVERDATA
[20:09:49] [Netty Client IO #9/INFO] [FML/]: Attempting connection with missing mods [] at SERVER
[20:09:49] [Netty Client IO #9/TRACE] [FML/]: $ModIdData:660 mappings->FMLHandshakeClientState$4:WAITINGSERVERCOMPLETE
[20:09:49] [Netty Client IO #9/INFO] [FML/]: Injecting existing block and item data into this client instance
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Registry consistency check successful
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Registry consistency check successful
[20:09:49] [Netty Client IO #9/TRACE] [mcp/mcp]: Sending event FMLModIdMappingEvent to mod mcp
[20:09:49] [Netty Client IO #9/TRACE] [mcp/mcp]: Sent event FMLModIdMappingEvent to mod mcp
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Coder Pack took 0,000s
[20:09:49] [Netty Client IO #9/TRACE] [FML/FML]: Sending event FMLModIdMappingEvent to mod FML
[20:09:49] [Netty Client IO #9/TRACE] [FML/FML]: Sent event FMLModIdMappingEvent to mod FML
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Bar Step: ModIdMapping - Forge Mod Loader took 0,000s
[20:09:49] [Netty Client IO #9/TRACE] [Forge/Forge]: Sending event FMLModIdMappingEvent to mod Forge
[20:09:49] [Netty Client IO #9/TRACE] [Forge/Forge]: Sent event FMLModIdMappingEvent to mod Forge
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Forge took 0,000s
[20:09:49] [Netty Client IO #9/TRACE] [Steamcraft/Steamcraft]: Sending event FMLModIdMappingEvent to mod Steamcraft
[20:09:49] [Netty Client IO #9/TRACE] [Steamcraft/Steamcraft]: Sent event FMLModIdMappingEvent to mod Steamcraft
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Bar Step: ModIdMapping - Flaxbeard's Steam Power took 0,000s
[20:09:49] [Netty Client IO #9/DEBUG] [FML/]: Bar Finished: ModIdMapping took 0,001s
[20:09:49] [Netty Client IO #9/INFO] [FML/]: Applying holder lookups
[20:09:49] [Netty Client IO #9/INFO] [FML/]: Holder lookups applied
[20:09:49] [Netty Client IO #9/TRACE] [FML/]: $HandshakeAck:{2}->FMLHandshakeClientState$5:PENDINGCOMPLETE
[20:09:49] [Netty Client IO #9/TRACE] [FML/]: $HandshakeAck:{3}->FMLHandshakeClientState$6:COMPLETE
[20:09:49] [Client thread/DEBUG] [FML/]: The fluid minecraft:lava has been selected as the default fluid for lava
[20:09:49] [Client thread/DEBUG] [FML/]: The fluid minecraft:water has been selected as the default fluid for water
[20:09:49] [Client thread/INFO] [FML/]: [Client thread] Client side modded connection established
[20:09:49] [Client thread/DEBUG] [FML/]: Overriding dimension: using 0
[20:09:49] [Client thread/DEBUG] [FML/]: Reverting to frozen data state.
[20:09:49] [Client thread/TRACE] [mcp/mcp]: Sending event FMLModIdMappingEvent to mod mcp
[20:09:49] [Client thread/TRACE] [mcp/mcp]: Sent event FMLModIdMappingEvent to mod mcp
[20:09:49] [Client thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Coder Pack took 0,000s
[20:09:49] [Client thread/TRACE] [FML/FML]: Sending event FMLModIdMappingEvent to mod FML
[20:09:49] [Client thread/TRACE] [FML/FML]: Sent event FMLModIdMappingEvent to mod FML
[20:09:49] [Client thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Forge Mod Loader took 0,000s
[20:09:49] [Client thread/TRACE] [Forge/Forge]: Sending event FMLModIdMappingEvent to mod Forge
[20:09:49] [Client thread/TRACE] [Forge/Forge]: Sent event FMLModIdMappingEvent to mod Forge
[20:09:49] [Client thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Minecraft Forge took 0,001s
[20:09:49] [Client thread/TRACE] [Steamcraft/Steamcraft]: Sending event FMLModIdMappingEvent to mod Steamcraft
[20:09:49] [Client thread/TRACE] [Steamcraft/Steamcraft]: Sent event FMLModIdMappingEvent to mod Steamcraft
[20:09:49] [Client thread/DEBUG] [FML/]: Bar Step: ModIdMapping - Flaxbeard's Steam Power took 0,000s
[20:09:49] [Client thread/DEBUG] [FML/]: Bar Finished: ModIdMapping took 0,001s
[20:09:49] [Client thread/INFO] [FML/]: Applying holder lookups
[20:09:49] [Client thread/INFO] [FML/]: Holder lookups applied
```

If you needed anything else just tell xD

**Comment by elifoster** [comment]
I don't see any error in that log...

**Comment by kindlich** [comment]
Me neither, but I had to add something xD

**Comment by elifoster** [comment]
I can't really do anything unless I see the error :frowning:

**Comment by ImportsExports** [comment]
Same issue here, works fine in single player but when on a server it kicks the user when they touch lava.  I do however have the server side error log which might help some.
Edit: The log I posted was when they logged in already touching lava, its slightly different from when they first touched it and were kicked.

Logged in and touched lava

```
[09:09:56] [Server thread/WARN]: Failed to handle packet for /PLAYERIP
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
    at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at flaxbeard.steamcraft.handler.PhobicCoatingHandler.walkOnFluid(PhobicCoatingHandler.java:97) ~[PhobicCoatingHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_614_PhobicCoatingHandler_walkOnFluid_PlayerTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350) ~[FMLCommonHandler.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353) ~[yz.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    ... 2 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
    at flaxbeard.steamcraft.handler.PhobicCoatingHandler.walkOnFluid(PhobicCoatingHandler.java:97) ~[PhobicCoatingHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_614_PhobicCoatingHandler_walkOnFluid_PlayerTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350) ~[FMLCommonHandler.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:353) ~[yz.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    ... 2 more
[09:09:56] [Server thread/INFO]: PLAYERID lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[09:09:56] [Server thread/INFO]: PLAYERID left the game
```

Attempting to log in touching lava

```
[09:13:26] [User Authenticator #5/INFO]: UUID of player PLAYERID is PLAYERUUID
[09:13:27] [Server thread/INFO]: PLAYERID[/PLAYERIP] logged in with entity id ### at (X, Y, Z)
[09:13:27] [Server thread/INFO]: PLAYERID joined the game
[09:13:27] [Server thread/INFO]: You whisper to PLAYERID: INTROMESSAGE
[09:13:28] [Server thread/WARN]: Failed to handle packet for /PLAYERIP
net.minecraft.util.ReportedException: Ticking player
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
    at fastcraft.at.a(F:978) [fastcraft-1.23.jar:?]
    at fastcraft.H.aq(F:36) [fastcraft-1.23.jar:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at flaxbeard.steamcraft.handler.PhobicCoatingHandler.walkOnFluid(PhobicCoatingHandler.java:97) ~[PhobicCoatingHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_614_PhobicCoatingHandler_walkOnFluid_PlayerTickEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
    at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
    at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
    at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
    at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
    ... 2 more
[09:13:28] [Server thread/INFO]: PLAYERID lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[09:13:28] [Server thread/INFO]: PLAYERID left the game
```

**Comment by elifoster** [comment]
Ah, yep. Trying to use the Minecraft class while on the server. That line also uses the wrong method to check if the key bind is down 😲
