### ISSUE TITLE
Sporadic ConcurrentModificationException

### ISSUE THREAD

**Issue by elifoster** [Esteemed-Innovation/Flaxbeards-Steam-Power#472]
## Description
This seemingly happens randomly. @Divineaspect if you wanted to figure out how this actually happens that'd be great... The code shouldn't be able to cause cmods.

## Base information
* Minecraft version: 1.10
* Minecraft Forge version: meh
* Flaxbeard's Steam Power version: 1.10

## Crash report
```
[20:44:21] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@256936d7:
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_60]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_60]
	at eiteam.esteemedinnovation.api.steamnet.SteamNetworkRegistry.onTick(SteamNetworkRegistry.java:58) ~[SteamNetworkRegistry.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_231_SteamNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) [FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:676) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) [IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
[20:44:21] [Server thread/ERROR] [FML]: Index: 6 Listeners:
[20:44:21] [Server thread/ERROR] [FML]: 0: NORMAL
[20:44:21] [Server thread/ERROR] [FML]: 1: ASM: WayofTime.bloodmagic.api.teleport.TeleportQueue@3004c204 serverTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:44:21] [Server thread/ERROR] [FML]: 2: ASM: Block{null} onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:44:21] [Server thread/ERROR] [FML]: 3: ASM: crazypants.enderio.conduit.ConduitNetworkTickHandler@61781c28 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:44:21] [Server thread/ERROR] [FML]: 4: ASM: com.enderio.core.common.util.Scheduler@789f02b0 onServerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:44:21] [Server thread/ERROR] [FML]: 5: ASM: crazypants.enderio.CommonProxy$TickTimer@3bc2a357 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:44:21] [Server thread/ERROR] [FML]: 6: ASM: eiteam.esteemedinnovation.api.steamnet.SteamNetworkRegistry@5d90cb31 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[20:44:21] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_60]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_60]
	at eiteam.esteemedinnovation.api.steamnet.SteamNetworkRegistry.onTick(SteamNetworkRegistry.java:58) ~[SteamNetworkRegistry.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_231_SteamNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:676) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156) ~[IntegratedServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
[20:44:21] [Server thread/ERROR]: This crash report has been saved to: /Users/elifoster/Desktop/Dev/Esteemed-Innovation/eclipse/./crash-reports/crash-2017-01-07_20.44.21-server.txt
[20:44:21] [Server thread/INFO]: Stopping server
[20:44:21] [Server thread/INFO]: Saving players
[20:44:21] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:649]: ---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 1/7/17 8:44 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at eiteam.esteemedinnovation.api.steamnet.SteamNetworkRegistry.onTick(SteamNetworkRegistry.java:58)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_231_SteamNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:676)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:536)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.12.1
	Java Version: 1.8.0_60, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 697732360 bytes (665 MB) / 1482686464 bytes (1414 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.32 Powered by Forge 12.18.1.2073 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forgeSrc-1.10.2-12.18.1.2073.jar) 
	UCHIJAAAA	Forge{12.18.1.2073} [Minecraft Forge] (forgeSrc-1.10.2-12.18.1.2073.jar) 
	UCHIJAAAA	CodeChickenLib{2.4.2.109} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.2.109-deobf.jar) 
	UCHIJAAAA	esteemedinnovation{@VERSION@} [Esteemed Innovation] (Esteemed-Innovation_main) 
	UCHIJAAAA	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UCHIJAAAA	JEI{3.9.0.246} [Just Enough Items] (jei_1.10.2-3.9.0.246.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.2-50} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.2-50.jar) 
	UCHIJAAAA	MineTweaker3{3.0.9} [MineTweaker 3] (CraftTweaker-1.9-3.0.9.jar) 
	UCHIJAAAA	enchiridion{3.1.6} [Enchiridion] (Enchiridion-1.9.4-3.1.6.jar) 
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJAAAA	endercore{1.10.2-0.4.1.51-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.51-beta.jar) 
	UCHIJAAAA	EnderIO{1.10.2-3.0.1.95_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.95_beta.jar) 
	Loaded coremods (and transformers): 
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.2.109-deobf.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.51-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/elifoster/.gradle/caches/modules-2/files-2.1/com.enderio/EnderIO/1.10.2-3.0.1.95_beta/1ef3b69e6282d723cffefdae2fada0f0efe756a7/EnderIO-1.10.2-3.0.1.95_beta.jar!/cofh/api/energy/TileEnergyHandler.class

	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['SatanicSanta'/163, l='New World', x=-1346.24, y=59.00, z=-2082.43]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
[20:44:21] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:printToSYSOUT:649]: #@!@# Game crashed! Crash report saved to: #@!@# ./crash-reports/crash-2017-01-07_20.44.21-server.txt
[20:44:21] [Client thread/INFO] [FML]: Waiting for the server to terminate/save.
[20:44:21] [Netty Local Client IO #0/INFO] [EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[20:44:21] [Server thread/INFO]: SatanicSanta lost connection: TextComponent{text='Server closed', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[20:44:21] [Server thread/INFO]: SatanicSanta left the game
[20:44:21] [Server thread/INFO]: Stopping singleplayer server as player logged out
[20:44:21] [Server thread/INFO]: Saving worlds
[20:44:21] [Server thread/INFO]: Saving chunks for level 'New World'/Overworld
[20:44:21] [Server thread/INFO]: Saving chunks for level 'New World'/Nether
[20:44:21] [Server thread/INFO]: Saving chunks for level 'New World'/The End
[20:44:22] [Server thread/INFO] [FML]: Unloading dimension 0
[20:44:22] [Server thread/INFO] [FML]: Unloading dimension -1
[20:44:22] [Server thread/INFO] [FML]: Unloading dimension 1
[20:44:22] [Server thread/INFO] [FML]: Applying holder lookups
[20:44:22] [Server thread/INFO] [FML]: Holder lookups applied
[20:44:22] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[20:44:22] [Client thread/INFO] [FML]: Server terminated.
[20:44:22] [Client Shutdown Thread/INFO]: Stopping server
[20:44:22] [Client Shutdown Thread/INFO]: Saving players
[20:44:22] [Client Shutdown Thread/INFO]: Saving worlds
Disconnected from the target VM, address: '127.0.0.1:61692', transport: 'socket'
AL lib: (EE) alc_cleanup: 1 device not closed

Process finished with exit code 255

```

**Comment by OvermindDL1** [comment]
From IRC:

> 12:38:44 OvermindDL1: Think I found it:  https://github.com/Esteemed-Innovation/Esteemed-Innovation/blob/0e5b830c712cbd677f57ca6653208cb5fa434701/src/api/java/eiteam/esteemedinnovation/api/tile/SteamTransporterTileEntity.java#L162
12:39:00 Explode is called from:  https://github.com/Esteemed-Innovation/Esteemed-Innovation/blob/a64dc92359181e72769e0e070fefcaf34889e91b/src/api/java/eiteam/esteemedinnovation/api/steamnet/SteamNetwork.java#L156
12:39:15 Which that tick() is called from https://github.com/Esteemed-Innovation/Esteemed-Innovation/blob/212c82cc816d3865e4c8572be1d95508966f3e7c/src/api/java/eiteam/esteemedinnovation/api/steamnet/SteamNetworkRegistry.java#L59
12:39:39 SatanicSanta: split calls add/remove as well
12:39:42 OvermindDL1: Thus the iterator calls tick, tick 'might' call explode, if it calls explode on a SteamTransporterTileEntity that will then grab the network and call split
12:39:47 And split calls add/remove
12:40:02 The explode should be queued up for the next TileEntity tick, not called from the network itself
12:40:22 SatanicSanta: yeah
12:40:25 good call
12:40:29 OvermindDL1: Any mutation calls should happen at a minecraft tick on the main thread is how I always did it, and never had an issue


So yeah, `SteamTransporterTileEntity`'s `explode` call calls into the network and mutates it while iteration happens, delay the explosion until the TileEntity's own tick event and that fixes it.
